# Do not edit. Generated by the configure script.
export PATH:=/Users/uu/node-v16.20.0/out/tools/bin:$(PATH)
BUILDTYPE=Release
NODE_TARGET_TYPE=executable
PYTHON=/Library/Developer/CommandLineTools/usr/bin/python3
PREFIX=/opt/node
